version: "2"

services:
  # cuckoo:
  #   image: blacktop/cuckoo:2.0
  #   command: daemon
  #   networks:
  #     - cuckoo
  web:
    image: blacktop/cuckoo:2.0
    ports:
      - "80:31337"
    links:
      - mongo
    command: web
    networks:
      - cuckoo
  api:
    image: blacktop/cuckoo:2.0
    ports:
      - "8000:1337"
    links:
      - mongo
    command: api
    networks:
      - cuckoo
  # web:
  #   build: nginx/.
  #   depends_on:
  #     - mongo
  #   ports:
  #     - "80:80"
  #   links:
  #     - mongo
  #   networks:
  #     - cuckoo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - cuckoo

networks:
  cuckoo:
    driver: bridge
