version: "2"

services:
  cuckoo:
    build: .
    ports:
      - "80:8000"
    links:
      - mongo
    command: /usr/bin/python manage.py runserver 0.0.0.0:8000
    networks:
      - cuckoo
  # web:
  #   build: nginx/.
  #   depends_on:
  #     - mongo
  #   ports:
  #     - "80:80"
  #   links:
  #     - mongo
  #   networks:
  #     - cuckoo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - cuckoo

networks:
  cuckoo:
    driver: bridge
