version: "2"

services:
  # cuckoo:
  #   image: blacktop/cuckoo:2.0
  #   command: daemon
  #   networks:
  #     - cuckoo
  web:
    image: blacktop/cuckoo
    ports:
      - "80:31337"
    links:
      - mongo
      - elasticsearch
    command: web
    networks:
      - cuckoo
  api:
    image: blacktop/cuckoo
    ports:
      - "8000:1337"
    links:
      - mongo
    command: api
    networks:
      - cuckoo
  # web:
  #   build: nginx/.
  #   depends_on:
  #     - mongo
  #   ports:
  #     - "80:80"
  #   links:
  #     - mongo
  #   networks:
  #     - cuckoo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - cuckoo-data:/data/db
    networks:
      - cuckoo
  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - cuckoo-data:/usr/share/elasticsearch/data
    networks:
      - cuckoo
postgres:
  image: postgres
  environment:
    POSTGRES_DB: cuckoo
    POSTGRES_USER: cuckoo
    POSTGRES_PASSWORD: cuckoo
  volumes:
    - cuckoo-data:/var/lib/postgresql/data
  networks:
    - cuckoo

volumes:
  cuckoo-data:

networks:
  cuckoo:
    driver: bridge
